// Code generated by scripts/gen_go.py from the bundled IDLs. DO NOT EDIT.
//
// Only the fixed-width prefix of each account is represented: every field up
// to the first variable-length one has a stable byte offset, and a launch's
// numbers all live in that prefix. Decoding stops cleanly when the buffer is
// shorter than the layout, which is the normal case for accounts written by
// an older build of the program.

package launchpad

import (
	"encoding/binary"
	"math"
)

var _ = math.Float64frombits

type PumpfunBondingCurve struct {
	VirtualTokenReserves uint64 // offset 0
	VirtualQuoteReserves uint64 // offset 8
	RealTokenReserves    uint64 // offset 16
	RealQuoteReserves    uint64 // offset 24
	TokenTotalSupply     uint64 // offset 32
	Complete             bool   // offset 40
	Creator              Pubkey // offset 41
	IsMayhemMode         bool   // offset 73
	IsCashbackCoin       bool   // offset 74
	QuoteMint            Pubkey // offset 75
	CreatorFeeBps        uint64 // offset 107
	CanEditCreatorFee    bool   // offset 115
	IsHolderReward       bool   // offset 116
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *PumpfunBondingCurve) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+8 > len(data) {
		return "virtual_token_reserves"
	}
	s.VirtualTokenReserves = binary.LittleEndian.Uint64(data[o:])
	if o = base + 8; o+8 > len(data) {
		return "virtual_quote_reserves"
	}
	s.VirtualQuoteReserves = binary.LittleEndian.Uint64(data[o:])
	if o = base + 16; o+8 > len(data) {
		return "real_token_reserves"
	}
	s.RealTokenReserves = binary.LittleEndian.Uint64(data[o:])
	if o = base + 24; o+8 > len(data) {
		return "real_quote_reserves"
	}
	s.RealQuoteReserves = binary.LittleEndian.Uint64(data[o:])
	if o = base + 32; o+8 > len(data) {
		return "token_total_supply"
	}
	s.TokenTotalSupply = binary.LittleEndian.Uint64(data[o:])
	if o = base + 40; o+1 > len(data) {
		return "complete"
	}
	s.Complete = data[o] == 1
	if o = base + 41; o+32 > len(data) {
		return "creator"
	}
	s.Creator = pubkeyAt(data, o)
	if o = base + 73; o+1 > len(data) {
		return "is_mayhem_mode"
	}
	s.IsMayhemMode = data[o] == 1
	if o = base + 74; o+1 > len(data) {
		return "is_cashback_coin"
	}
	s.IsCashbackCoin = data[o] == 1
	if o = base + 75; o+32 > len(data) {
		return "quote_mint"
	}
	s.QuoteMint = pubkeyAt(data, o)
	if o = base + 107; o+8 > len(data) {
		return "creator_fee_bps"
	}
	s.CreatorFeeBps = binary.LittleEndian.Uint64(data[o:])
	if o = base + 115; o+1 > len(data) {
		return "can_edit_creator_fee"
	}
	s.CanEditCreatorFee = data[o] == 1
	if o = base + 116; o+1 > len(data) {
		return "is_holder_reward"
	}
	s.IsHolderReward = data[o] == 1
	return ""
}

type PumpfunGlobal struct {
	Initialized                  bool      // offset 0
	Authority                    Pubkey    // offset 1
	FeeRecipient                 Pubkey    // offset 33
	InitialVirtualTokenReserves  uint64    // offset 65
	InitialVirtualSolReserves    uint64    // offset 73
	InitialRealTokenReserves     uint64    // offset 81
	TokenTotalSupply             uint64    // offset 89
	FeeBasisPoints               uint64    // offset 97
	WithdrawAuthority            Pubkey    // offset 105
	EnableMigrate                bool      // offset 137
	PoolMigrationFee             uint64    // offset 138
	CreatorFeeBasisPoints        uint64    // offset 146
	FeeRecipients                [7]Pubkey // offset 154
	SetCreatorAuthority          Pubkey    // offset 378
	AdminSetCreatorAuthority     Pubkey    // offset 410
	CreateV2Enabled              bool      // offset 442
	WhitelistPda                 Pubkey    // offset 443
	ReservedFeeRecipient         Pubkey    // offset 475
	MayhemModeEnabled            bool      // offset 507
	ReservedFeeRecipients        [7]Pubkey // offset 508
	IsCashbackEnabled            bool      // offset 732
	BuybackFeeRecipients         [8]Pubkey // offset 733
	BuybackBasisPoints           uint64    // offset 989
	InitialVirtualQuoteReserves  uint64    // offset 997
	WhitelistedQuoteMints        [1]Pubkey // offset 1005
	CreatorFeeConfigurable       bool      // offset 1037
	MaxConfigurableCreatorFeeBps uint64    // offset 1038
	HolderRewardClaimAuthority   Pubkey    // offset 1046
	IsHolderRewardEnabled        bool      // offset 1078
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *PumpfunGlobal) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+1 > len(data) {
		return "initialized"
	}
	s.Initialized = data[o] == 1
	if o = base + 1; o+32 > len(data) {
		return "authority"
	}
	s.Authority = pubkeyAt(data, o)
	if o = base + 33; o+32 > len(data) {
		return "fee_recipient"
	}
	s.FeeRecipient = pubkeyAt(data, o)
	if o = base + 65; o+8 > len(data) {
		return "initial_virtual_token_reserves"
	}
	s.InitialVirtualTokenReserves = binary.LittleEndian.Uint64(data[o:])
	if o = base + 73; o+8 > len(data) {
		return "initial_virtual_sol_reserves"
	}
	s.InitialVirtualSolReserves = binary.LittleEndian.Uint64(data[o:])
	if o = base + 81; o+8 > len(data) {
		return "initial_real_token_reserves"
	}
	s.InitialRealTokenReserves = binary.LittleEndian.Uint64(data[o:])
	if o = base + 89; o+8 > len(data) {
		return "token_total_supply"
	}
	s.TokenTotalSupply = binary.LittleEndian.Uint64(data[o:])
	if o = base + 97; o+8 > len(data) {
		return "fee_basis_points"
	}
	s.FeeBasisPoints = binary.LittleEndian.Uint64(data[o:])
	if o = base + 105; o+32 > len(data) {
		return "withdraw_authority"
	}
	s.WithdrawAuthority = pubkeyAt(data, o)
	if o = base + 137; o+1 > len(data) {
		return "enable_migrate"
	}
	s.EnableMigrate = data[o] == 1
	if o = base + 138; o+8 > len(data) {
		return "pool_migration_fee"
	}
	s.PoolMigrationFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 146; o+8 > len(data) {
		return "creator_fee_basis_points"
	}
	s.CreatorFeeBasisPoints = binary.LittleEndian.Uint64(data[o:])
	if o = base + 154; o+224 > len(data) {
		return "fee_recipients"
	}
	for i := 0; i < 7; i++ {
		o = base + 154 + i*32
		s.FeeRecipients[i] = pubkeyAt(data, o)
	}
	if o = base + 378; o+32 > len(data) {
		return "set_creator_authority"
	}
	s.SetCreatorAuthority = pubkeyAt(data, o)
	if o = base + 410; o+32 > len(data) {
		return "admin_set_creator_authority"
	}
	s.AdminSetCreatorAuthority = pubkeyAt(data, o)
	if o = base + 442; o+1 > len(data) {
		return "create_v2_enabled"
	}
	s.CreateV2Enabled = data[o] == 1
	if o = base + 443; o+32 > len(data) {
		return "whitelist_pda"
	}
	s.WhitelistPda = pubkeyAt(data, o)
	if o = base + 475; o+32 > len(data) {
		return "reserved_fee_recipient"
	}
	s.ReservedFeeRecipient = pubkeyAt(data, o)
	if o = base + 507; o+1 > len(data) {
		return "mayhem_mode_enabled"
	}
	s.MayhemModeEnabled = data[o] == 1
	if o = base + 508; o+224 > len(data) {
		return "reserved_fee_recipients"
	}
	for i := 0; i < 7; i++ {
		o = base + 508 + i*32
		s.ReservedFeeRecipients[i] = pubkeyAt(data, o)
	}
	if o = base + 732; o+1 > len(data) {
		return "is_cashback_enabled"
	}
	s.IsCashbackEnabled = data[o] == 1
	if o = base + 733; o+256 > len(data) {
		return "buyback_fee_recipients"
	}
	for i := 0; i < 8; i++ {
		o = base + 733 + i*32
		s.BuybackFeeRecipients[i] = pubkeyAt(data, o)
	}
	if o = base + 989; o+8 > len(data) {
		return "buyback_basis_points"
	}
	s.BuybackBasisPoints = binary.LittleEndian.Uint64(data[o:])
	if o = base + 997; o+8 > len(data) {
		return "initial_virtual_quote_reserves"
	}
	s.InitialVirtualQuoteReserves = binary.LittleEndian.Uint64(data[o:])
	if o = base + 1005; o+32 > len(data) {
		return "whitelisted_quote_mints"
	}
	for i := 0; i < 1; i++ {
		o = base + 1005 + i*32
		s.WhitelistedQuoteMints[i] = pubkeyAt(data, o)
	}
	if o = base + 1037; o+1 > len(data) {
		return "creator_fee_configurable"
	}
	s.CreatorFeeConfigurable = data[o] == 1
	if o = base + 1038; o+8 > len(data) {
		return "max_configurable_creator_fee_bps"
	}
	s.MaxConfigurableCreatorFeeBps = binary.LittleEndian.Uint64(data[o:])
	if o = base + 1046; o+32 > len(data) {
		return "holder_reward_claim_authority"
	}
	s.HolderRewardClaimAuthority = pubkeyAt(data, o)
	if o = base + 1078; o+1 > len(data) {
		return "is_holder_reward_enabled"
	}
	s.IsHolderRewardEnabled = data[o] == 1
	return ""
}

type PumpswapPool struct {
	PoolBump              uint8  // offset 0
	Index                 uint16 // offset 1
	Creator               Pubkey // offset 3
	BaseMint              Pubkey // offset 35
	QuoteMint             Pubkey // offset 67
	LPMint                Pubkey // offset 99
	PoolBaseTokenAccount  Pubkey // offset 131
	PoolQuoteTokenAccount Pubkey // offset 163
	LPSupply              uint64 // offset 195
	CoinCreator           Pubkey // offset 203
	IsMayhemMode          bool   // offset 235
	IsCashbackCoin        bool   // offset 236
	VirtualQuoteReserves  U128   // offset 237
	CreatorFeeBps         uint64 // offset 253
	CanEditCreatorFee     bool   // offset 261
	IsHolderReward        bool   // offset 262
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *PumpswapPool) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+1 > len(data) {
		return "pool_bump"
	}
	s.PoolBump = data[o]
	if o = base + 1; o+2 > len(data) {
		return "index"
	}
	s.Index = binary.LittleEndian.Uint16(data[o:])
	if o = base + 3; o+32 > len(data) {
		return "creator"
	}
	s.Creator = pubkeyAt(data, o)
	if o = base + 35; o+32 > len(data) {
		return "base_mint"
	}
	s.BaseMint = pubkeyAt(data, o)
	if o = base + 67; o+32 > len(data) {
		return "quote_mint"
	}
	s.QuoteMint = pubkeyAt(data, o)
	if o = base + 99; o+32 > len(data) {
		return "lp_mint"
	}
	s.LPMint = pubkeyAt(data, o)
	if o = base + 131; o+32 > len(data) {
		return "pool_base_token_account"
	}
	s.PoolBaseTokenAccount = pubkeyAt(data, o)
	if o = base + 163; o+32 > len(data) {
		return "pool_quote_token_account"
	}
	s.PoolQuoteTokenAccount = pubkeyAt(data, o)
	if o = base + 195; o+8 > len(data) {
		return "lp_supply"
	}
	s.LPSupply = binary.LittleEndian.Uint64(data[o:])
	if o = base + 203; o+32 > len(data) {
		return "coin_creator"
	}
	s.CoinCreator = pubkeyAt(data, o)
	if o = base + 235; o+1 > len(data) {
		return "is_mayhem_mode"
	}
	s.IsMayhemMode = data[o] == 1
	if o = base + 236; o+1 > len(data) {
		return "is_cashback_coin"
	}
	s.IsCashbackCoin = data[o] == 1
	if o = base + 237; o+16 > len(data) {
		return "virtual_quote_reserves"
	}
	s.VirtualQuoteReserves = u128At(data, o)
	if o = base + 253; o+8 > len(data) {
		return "creator_fee_bps"
	}
	s.CreatorFeeBps = binary.LittleEndian.Uint64(data[o:])
	if o = base + 261; o+1 > len(data) {
		return "can_edit_creator_fee"
	}
	s.CanEditCreatorFee = data[o] == 1
	if o = base + 262; o+1 > len(data) {
		return "is_holder_reward"
	}
	s.IsHolderReward = data[o] == 1
	return ""
}

type PumpswapGlobalConfig struct {
	Admin                        Pubkey    // offset 0
	LPFeeBasisPoints             uint64    // offset 32
	ProtocolFeeBasisPoints       uint64    // offset 40
	DisableFlags                 uint8     // offset 48
	ProtocolFeeRecipients        [8]Pubkey // offset 49
	CoinCreatorFeeBasisPoints    uint64    // offset 305
	AdminSetCoinCreatorAuthority Pubkey    // offset 313
	WhitelistPda                 Pubkey    // offset 345
	ReservedFeeRecipient         Pubkey    // offset 377
	MayhemModeEnabled            bool      // offset 409
	ReservedFeeRecipients        [7]Pubkey // offset 410
	IsCashbackEnabled            bool      // offset 634
	BuybackFeeRecipients         [8]Pubkey // offset 635
	BuybackBasisPoints           uint64    // offset 891
	BoostAuthority               Pubkey    // offset 899
	BoostEnabled                 bool      // offset 931
	CreatorFeeConfigurable       bool      // offset 932
	MaxConfigurableCreatorFeeBps uint64    // offset 933
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *PumpswapGlobalConfig) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+32 > len(data) {
		return "admin"
	}
	s.Admin = pubkeyAt(data, o)
	if o = base + 32; o+8 > len(data) {
		return "lp_fee_basis_points"
	}
	s.LPFeeBasisPoints = binary.LittleEndian.Uint64(data[o:])
	if o = base + 40; o+8 > len(data) {
		return "protocol_fee_basis_points"
	}
	s.ProtocolFeeBasisPoints = binary.LittleEndian.Uint64(data[o:])
	if o = base + 48; o+1 > len(data) {
		return "disable_flags"
	}
	s.DisableFlags = data[o]
	if o = base + 49; o+256 > len(data) {
		return "protocol_fee_recipients"
	}
	for i := 0; i < 8; i++ {
		o = base + 49 + i*32
		s.ProtocolFeeRecipients[i] = pubkeyAt(data, o)
	}
	if o = base + 305; o+8 > len(data) {
		return "coin_creator_fee_basis_points"
	}
	s.CoinCreatorFeeBasisPoints = binary.LittleEndian.Uint64(data[o:])
	if o = base + 313; o+32 > len(data) {
		return "admin_set_coin_creator_authority"
	}
	s.AdminSetCoinCreatorAuthority = pubkeyAt(data, o)
	if o = base + 345; o+32 > len(data) {
		return "whitelist_pda"
	}
	s.WhitelistPda = pubkeyAt(data, o)
	if o = base + 377; o+32 > len(data) {
		return "reserved_fee_recipient"
	}
	s.ReservedFeeRecipient = pubkeyAt(data, o)
	if o = base + 409; o+1 > len(data) {
		return "mayhem_mode_enabled"
	}
	s.MayhemModeEnabled = data[o] == 1
	if o = base + 410; o+224 > len(data) {
		return "reserved_fee_recipients"
	}
	for i := 0; i < 7; i++ {
		o = base + 410 + i*32
		s.ReservedFeeRecipients[i] = pubkeyAt(data, o)
	}
	if o = base + 634; o+1 > len(data) {
		return "is_cashback_enabled"
	}
	s.IsCashbackEnabled = data[o] == 1
	if o = base + 635; o+256 > len(data) {
		return "buyback_fee_recipients"
	}
	for i := 0; i < 8; i++ {
		o = base + 635 + i*32
		s.BuybackFeeRecipients[i] = pubkeyAt(data, o)
	}
	if o = base + 891; o+8 > len(data) {
		return "buyback_basis_points"
	}
	s.BuybackBasisPoints = binary.LittleEndian.Uint64(data[o:])
	if o = base + 899; o+32 > len(data) {
		return "boost_authority"
	}
	s.BoostAuthority = pubkeyAt(data, o)
	if o = base + 931; o+1 > len(data) {
		return "boost_enabled"
	}
	s.BoostEnabled = data[o] == 1
	if o = base + 932; o+1 > len(data) {
		return "creator_fee_configurable"
	}
	s.CreatorFeeConfigurable = data[o] == 1
	if o = base + 933; o+8 > len(data) {
		return "max_configurable_creator_fee_bps"
	}
	s.MaxConfigurableCreatorFeeBps = binary.LittleEndian.Uint64(data[o:])
	return ""
}

type RaydiumLaunchlabPoolState struct {
	Epoch                 uint64                          // offset 0
	AuthBump              uint8                           // offset 8
	Status                uint8                           // offset 9
	BaseDecimals          uint8                           // offset 10
	QuoteDecimals         uint8                           // offset 11
	MigrateType           uint8                           // offset 12
	Supply                uint64                          // offset 13
	TotalBaseSell         uint64                          // offset 21
	VirtualBase           uint64                          // offset 29
	VirtualQuote          uint64                          // offset 37
	RealBase              uint64                          // offset 45
	RealQuote             uint64                          // offset 53
	TotalQuoteFundRaising uint64                          // offset 61
	QuoteProtocolFee      uint64                          // offset 69
	PlatformFee           uint64                          // offset 77
	MigrateFee            uint64                          // offset 85
	VestingSchedule       RaydiumLaunchlabVestingSchedule // offset 93
	GlobalConfig          Pubkey                          // offset 133
	PlatformConfig        Pubkey                          // offset 165
	BaseMint              Pubkey                          // offset 197
	QuoteMint             Pubkey                          // offset 229
	BaseVault             Pubkey                          // offset 261
	QuoteVault            Pubkey                          // offset 293
	Creator               Pubkey                          // offset 325
	TokenProgramFlag      uint8                           // offset 357
	AMMCreatorFeeOn       uint8                           // offset 358
	PlatformVestingShare  uint64                          // offset 359
	Padding               [54]uint8                       // offset 367
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *RaydiumLaunchlabPoolState) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+8 > len(data) {
		return "epoch"
	}
	s.Epoch = binary.LittleEndian.Uint64(data[o:])
	if o = base + 8; o+1 > len(data) {
		return "auth_bump"
	}
	s.AuthBump = data[o]
	if o = base + 9; o+1 > len(data) {
		return "status"
	}
	s.Status = data[o]
	if o = base + 10; o+1 > len(data) {
		return "base_decimals"
	}
	s.BaseDecimals = data[o]
	if o = base + 11; o+1 > len(data) {
		return "quote_decimals"
	}
	s.QuoteDecimals = data[o]
	if o = base + 12; o+1 > len(data) {
		return "migrate_type"
	}
	s.MigrateType = data[o]
	if o = base + 13; o+8 > len(data) {
		return "supply"
	}
	s.Supply = binary.LittleEndian.Uint64(data[o:])
	if o = base + 21; o+8 > len(data) {
		return "total_base_sell"
	}
	s.TotalBaseSell = binary.LittleEndian.Uint64(data[o:])
	if o = base + 29; o+8 > len(data) {
		return "virtual_base"
	}
	s.VirtualBase = binary.LittleEndian.Uint64(data[o:])
	if o = base + 37; o+8 > len(data) {
		return "virtual_quote"
	}
	s.VirtualQuote = binary.LittleEndian.Uint64(data[o:])
	if o = base + 45; o+8 > len(data) {
		return "real_base"
	}
	s.RealBase = binary.LittleEndian.Uint64(data[o:])
	if o = base + 53; o+8 > len(data) {
		return "real_quote"
	}
	s.RealQuote = binary.LittleEndian.Uint64(data[o:])
	if o = base + 61; o+8 > len(data) {
		return "total_quote_fund_raising"
	}
	s.TotalQuoteFundRaising = binary.LittleEndian.Uint64(data[o:])
	if o = base + 69; o+8 > len(data) {
		return "quote_protocol_fee"
	}
	s.QuoteProtocolFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 77; o+8 > len(data) {
		return "platform_fee"
	}
	s.PlatformFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 85; o+8 > len(data) {
		return "migrate_fee"
	}
	s.MigrateFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 93; o+40 > len(data) {
		return "vesting_schedule"
	}
	s.VestingSchedule.decodeAt(data, o)
	if o = base + 133; o+32 > len(data) {
		return "global_config"
	}
	s.GlobalConfig = pubkeyAt(data, o)
	if o = base + 165; o+32 > len(data) {
		return "platform_config"
	}
	s.PlatformConfig = pubkeyAt(data, o)
	if o = base + 197; o+32 > len(data) {
		return "base_mint"
	}
	s.BaseMint = pubkeyAt(data, o)
	if o = base + 229; o+32 > len(data) {
		return "quote_mint"
	}
	s.QuoteMint = pubkeyAt(data, o)
	if o = base + 261; o+32 > len(data) {
		return "base_vault"
	}
	s.BaseVault = pubkeyAt(data, o)
	if o = base + 293; o+32 > len(data) {
		return "quote_vault"
	}
	s.QuoteVault = pubkeyAt(data, o)
	if o = base + 325; o+32 > len(data) {
		return "creator"
	}
	s.Creator = pubkeyAt(data, o)
	if o = base + 357; o+1 > len(data) {
		return "token_program_flag"
	}
	s.TokenProgramFlag = data[o]
	if o = base + 358; o+1 > len(data) {
		return "amm_creator_fee_on"
	}
	s.AMMCreatorFeeOn = data[o]
	if o = base + 359; o+8 > len(data) {
		return "platform_vesting_share"
	}
	s.PlatformVestingShare = binary.LittleEndian.Uint64(data[o:])
	if o = base + 367; o+54 > len(data) {
		return "padding"
	}
	for i := 0; i < 54; i++ {
		o = base + 367 + i*1
		s.Padding[i] = data[o]
	}
	return ""
}

type RaydiumLaunchlabVestingSchedule struct {
	TotalLockedAmount    uint64 // offset 0
	CliffPeriod          uint64 // offset 8
	UnlockPeriod         uint64 // offset 16
	StartTime            uint64 // offset 24
	AllocatedShareAmount uint64 // offset 32
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *RaydiumLaunchlabVestingSchedule) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+8 > len(data) {
		return "total_locked_amount"
	}
	s.TotalLockedAmount = binary.LittleEndian.Uint64(data[o:])
	if o = base + 8; o+8 > len(data) {
		return "cliff_period"
	}
	s.CliffPeriod = binary.LittleEndian.Uint64(data[o:])
	if o = base + 16; o+8 > len(data) {
		return "unlock_period"
	}
	s.UnlockPeriod = binary.LittleEndian.Uint64(data[o:])
	if o = base + 24; o+8 > len(data) {
		return "start_time"
	}
	s.StartTime = binary.LittleEndian.Uint64(data[o:])
	if o = base + 32; o+8 > len(data) {
		return "allocated_share_amount"
	}
	s.AllocatedShareAmount = binary.LittleEndian.Uint64(data[o:])
	return ""
}

type RaydiumLaunchlabGlobalConfig struct {
	Epoch                 uint64     // offset 0
	CurveType             uint8      // offset 8
	Index                 uint16     // offset 9
	MigrateFee            uint64     // offset 11
	TradeFeeRate          uint64     // offset 19
	MaxShareFeeRate       uint64     // offset 27
	MinBaseSupply         uint64     // offset 35
	MaxLockRate           uint64     // offset 43
	MinBaseSellRate       uint64     // offset 51
	MinBaseMigrateRate    uint64     // offset 59
	MinQuoteFundRaising   uint64     // offset 67
	QuoteMint             Pubkey     // offset 75
	ProtocolFeeOwner      Pubkey     // offset 107
	MigrateFeeOwner       Pubkey     // offset 139
	MigrateToAmmWallet    Pubkey     // offset 171
	MigrateToCpswapWallet Pubkey     // offset 203
	RequiresPlatformAuth  uint8      // offset 235
	PaddingAlignment      [7]uint8   // offset 236
	Padding               [15]uint64 // offset 243
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *RaydiumLaunchlabGlobalConfig) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+8 > len(data) {
		return "epoch"
	}
	s.Epoch = binary.LittleEndian.Uint64(data[o:])
	if o = base + 8; o+1 > len(data) {
		return "curve_type"
	}
	s.CurveType = data[o]
	if o = base + 9; o+2 > len(data) {
		return "index"
	}
	s.Index = binary.LittleEndian.Uint16(data[o:])
	if o = base + 11; o+8 > len(data) {
		return "migrate_fee"
	}
	s.MigrateFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 19; o+8 > len(data) {
		return "trade_fee_rate"
	}
	s.TradeFeeRate = binary.LittleEndian.Uint64(data[o:])
	if o = base + 27; o+8 > len(data) {
		return "max_share_fee_rate"
	}
	s.MaxShareFeeRate = binary.LittleEndian.Uint64(data[o:])
	if o = base + 35; o+8 > len(data) {
		return "min_base_supply"
	}
	s.MinBaseSupply = binary.LittleEndian.Uint64(data[o:])
	if o = base + 43; o+8 > len(data) {
		return "max_lock_rate"
	}
	s.MaxLockRate = binary.LittleEndian.Uint64(data[o:])
	if o = base + 51; o+8 > len(data) {
		return "min_base_sell_rate"
	}
	s.MinBaseSellRate = binary.LittleEndian.Uint64(data[o:])
	if o = base + 59; o+8 > len(data) {
		return "min_base_migrate_rate"
	}
	s.MinBaseMigrateRate = binary.LittleEndian.Uint64(data[o:])
	if o = base + 67; o+8 > len(data) {
		return "min_quote_fund_raising"
	}
	s.MinQuoteFundRaising = binary.LittleEndian.Uint64(data[o:])
	if o = base + 75; o+32 > len(data) {
		return "quote_mint"
	}
	s.QuoteMint = pubkeyAt(data, o)
	if o = base + 107; o+32 > len(data) {
		return "protocol_fee_owner"
	}
	s.ProtocolFeeOwner = pubkeyAt(data, o)
	if o = base + 139; o+32 > len(data) {
		return "migrate_fee_owner"
	}
	s.MigrateFeeOwner = pubkeyAt(data, o)
	if o = base + 171; o+32 > len(data) {
		return "migrate_to_amm_wallet"
	}
	s.MigrateToAmmWallet = pubkeyAt(data, o)
	if o = base + 203; o+32 > len(data) {
		return "migrate_to_cpswap_wallet"
	}
	s.MigrateToCpswapWallet = pubkeyAt(data, o)
	if o = base + 235; o+1 > len(data) {
		return "requires_platform_auth"
	}
	s.RequiresPlatformAuth = data[o]
	if o = base + 236; o+7 > len(data) {
		return "padding_alignment"
	}
	for i := 0; i < 7; i++ {
		o = base + 236 + i*1
		s.PaddingAlignment[i] = data[o]
	}
	if o = base + 243; o+120 > len(data) {
		return "padding"
	}
	for i := 0; i < 15; i++ {
		o = base + 243 + i*8
		s.Padding[i] = binary.LittleEndian.Uint64(data[o:])
	}
	return ""
}

type RaydiumLaunchlabPlatformConfig struct {
	Epoch                    uint64     // offset 0
	PlatformFeeWallet        Pubkey     // offset 8
	PlatformNftWallet        Pubkey     // offset 40
	PlatformScale            uint64     // offset 72
	CreatorScale             uint64     // offset 80
	BurnScale                uint64     // offset 88
	FeeRate                  uint64     // offset 96
	Name                     [64]uint8  // offset 104
	Web                      [256]uint8 // offset 168
	Img                      [256]uint8 // offset 424
	CpswapConfig             Pubkey     // offset 680
	CreatorFeeRate           uint64     // offset 712
	TransferFeeExtensionAuth Pubkey     // offset 720
	PlatformVestingWallet    Pubkey     // offset 752
	PlatformVestingScale     uint64     // offset 784
	PlatformCpCreator        Pubkey     // offset 792
	Padding                  [108]uint8 // offset 824
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *RaydiumLaunchlabPlatformConfig) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+8 > len(data) {
		return "epoch"
	}
	s.Epoch = binary.LittleEndian.Uint64(data[o:])
	if o = base + 8; o+32 > len(data) {
		return "platform_fee_wallet"
	}
	s.PlatformFeeWallet = pubkeyAt(data, o)
	if o = base + 40; o+32 > len(data) {
		return "platform_nft_wallet"
	}
	s.PlatformNftWallet = pubkeyAt(data, o)
	if o = base + 72; o+8 > len(data) {
		return "platform_scale"
	}
	s.PlatformScale = binary.LittleEndian.Uint64(data[o:])
	if o = base + 80; o+8 > len(data) {
		return "creator_scale"
	}
	s.CreatorScale = binary.LittleEndian.Uint64(data[o:])
	if o = base + 88; o+8 > len(data) {
		return "burn_scale"
	}
	s.BurnScale = binary.LittleEndian.Uint64(data[o:])
	if o = base + 96; o+8 > len(data) {
		return "fee_rate"
	}
	s.FeeRate = binary.LittleEndian.Uint64(data[o:])
	if o = base + 104; o+64 > len(data) {
		return "name"
	}
	for i := 0; i < 64; i++ {
		o = base + 104 + i*1
		s.Name[i] = data[o]
	}
	if o = base + 168; o+256 > len(data) {
		return "web"
	}
	for i := 0; i < 256; i++ {
		o = base + 168 + i*1
		s.Web[i] = data[o]
	}
	if o = base + 424; o+256 > len(data) {
		return "img"
	}
	for i := 0; i < 256; i++ {
		o = base + 424 + i*1
		s.Img[i] = data[o]
	}
	if o = base + 680; o+32 > len(data) {
		return "cpswap_config"
	}
	s.CpswapConfig = pubkeyAt(data, o)
	if o = base + 712; o+8 > len(data) {
		return "creator_fee_rate"
	}
	s.CreatorFeeRate = binary.LittleEndian.Uint64(data[o:])
	if o = base + 720; o+32 > len(data) {
		return "transfer_fee_extension_auth"
	}
	s.TransferFeeExtensionAuth = pubkeyAt(data, o)
	if o = base + 752; o+32 > len(data) {
		return "platform_vesting_wallet"
	}
	s.PlatformVestingWallet = pubkeyAt(data, o)
	if o = base + 784; o+8 > len(data) {
		return "platform_vesting_scale"
	}
	s.PlatformVestingScale = binary.LittleEndian.Uint64(data[o:])
	if o = base + 792; o+32 > len(data) {
		return "platform_cp_creator"
	}
	s.PlatformCpCreator = pubkeyAt(data, o)
	if o = base + 824; o+108 > len(data) {
		return "padding"
	}
	for i := 0; i < 108; i++ {
		o = base + 824 + i*1
		s.Padding[i] = data[o]
	}
	return ""
}

type MeteoraDbcVirtualPool struct {
	VolatilityTracker          MeteoraDbcVolatilityTracker // offset 0
	Config                     Pubkey                      // offset 64
	Creator                    Pubkey                      // offset 96
	BaseMint                   Pubkey                      // offset 128
	BaseVault                  Pubkey                      // offset 160
	QuoteVault                 Pubkey                      // offset 192
	BaseReserve                uint64                      // offset 224
	QuoteReserve               uint64                      // offset 232
	ProtocolBaseFee            uint64                      // offset 240
	ProtocolQuoteFee           uint64                      // offset 248
	PartnerBaseFee             uint64                      // offset 256
	PartnerQuoteFee            uint64                      // offset 264
	SqrtPrice                  U128                        // offset 272
	ActivationPoint            uint64                      // offset 288
	PoolType                   uint8                       // offset 296
	IsMigrated                 uint8                       // offset 297
	IsPartnerWithdrawSurplus   uint8                       // offset 298
	IsProtocolWithdrawSurplus  uint8                       // offset 299
	MigrationProgress          uint8                       // offset 300
	IsWithdrawLeftover         uint8                       // offset 301
	IsCreatorWithdrawSurplus   uint8                       // offset 302
	MigrationFeeWithdrawStatus uint8                       // offset 303
	Metrics                    MeteoraDbcPoolMetrics       // offset 304
	FinishCurveTimestamp       uint64                      // offset 336
	CreatorBaseFee             uint64                      // offset 344
	CreatorQuoteFee            uint64                      // offset 352
	Padding1                   [7]uint64                   // offset 360
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *MeteoraDbcVirtualPool) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+64 > len(data) {
		return "volatility_tracker"
	}
	s.VolatilityTracker.decodeAt(data, o)
	if o = base + 64; o+32 > len(data) {
		return "config"
	}
	s.Config = pubkeyAt(data, o)
	if o = base + 96; o+32 > len(data) {
		return "creator"
	}
	s.Creator = pubkeyAt(data, o)
	if o = base + 128; o+32 > len(data) {
		return "base_mint"
	}
	s.BaseMint = pubkeyAt(data, o)
	if o = base + 160; o+32 > len(data) {
		return "base_vault"
	}
	s.BaseVault = pubkeyAt(data, o)
	if o = base + 192; o+32 > len(data) {
		return "quote_vault"
	}
	s.QuoteVault = pubkeyAt(data, o)
	if o = base + 224; o+8 > len(data) {
		return "base_reserve"
	}
	s.BaseReserve = binary.LittleEndian.Uint64(data[o:])
	if o = base + 232; o+8 > len(data) {
		return "quote_reserve"
	}
	s.QuoteReserve = binary.LittleEndian.Uint64(data[o:])
	if o = base + 240; o+8 > len(data) {
		return "protocol_base_fee"
	}
	s.ProtocolBaseFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 248; o+8 > len(data) {
		return "protocol_quote_fee"
	}
	s.ProtocolQuoteFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 256; o+8 > len(data) {
		return "partner_base_fee"
	}
	s.PartnerBaseFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 264; o+8 > len(data) {
		return "partner_quote_fee"
	}
	s.PartnerQuoteFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 272; o+16 > len(data) {
		return "sqrt_price"
	}
	s.SqrtPrice = u128At(data, o)
	if o = base + 288; o+8 > len(data) {
		return "activation_point"
	}
	s.ActivationPoint = binary.LittleEndian.Uint64(data[o:])
	if o = base + 296; o+1 > len(data) {
		return "pool_type"
	}
	s.PoolType = data[o]
	if o = base + 297; o+1 > len(data) {
		return "is_migrated"
	}
	s.IsMigrated = data[o]
	if o = base + 298; o+1 > len(data) {
		return "is_partner_withdraw_surplus"
	}
	s.IsPartnerWithdrawSurplus = data[o]
	if o = base + 299; o+1 > len(data) {
		return "is_protocol_withdraw_surplus"
	}
	s.IsProtocolWithdrawSurplus = data[o]
	if o = base + 300; o+1 > len(data) {
		return "migration_progress"
	}
	s.MigrationProgress = data[o]
	if o = base + 301; o+1 > len(data) {
		return "is_withdraw_leftover"
	}
	s.IsWithdrawLeftover = data[o]
	if o = base + 302; o+1 > len(data) {
		return "is_creator_withdraw_surplus"
	}
	s.IsCreatorWithdrawSurplus = data[o]
	if o = base + 303; o+1 > len(data) {
		return "migration_fee_withdraw_status"
	}
	s.MigrationFeeWithdrawStatus = data[o]
	if o = base + 304; o+32 > len(data) {
		return "metrics"
	}
	s.Metrics.decodeAt(data, o)
	if o = base + 336; o+8 > len(data) {
		return "finish_curve_timestamp"
	}
	s.FinishCurveTimestamp = binary.LittleEndian.Uint64(data[o:])
	if o = base + 344; o+8 > len(data) {
		return "creator_base_fee"
	}
	s.CreatorBaseFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 352; o+8 > len(data) {
		return "creator_quote_fee"
	}
	s.CreatorQuoteFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 360; o+56 > len(data) {
		return "_padding_1"
	}
	for i := 0; i < 7; i++ {
		o = base + 360 + i*8
		s.Padding1[i] = binary.LittleEndian.Uint64(data[o:])
	}
	return ""
}

type MeteoraDbcVolatilityTracker struct {
	LastUpdateTimestamp   uint64   // offset 0
	Padding               [8]uint8 // offset 8
	SqrtPriceReference    U128     // offset 16
	VolatilityAccumulator U128     // offset 32
	VolatilityReference   U128     // offset 48
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *MeteoraDbcVolatilityTracker) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+8 > len(data) {
		return "last_update_timestamp"
	}
	s.LastUpdateTimestamp = binary.LittleEndian.Uint64(data[o:])
	if o = base + 8; o+8 > len(data) {
		return "padding"
	}
	for i := 0; i < 8; i++ {
		o = base + 8 + i*1
		s.Padding[i] = data[o]
	}
	if o = base + 16; o+16 > len(data) {
		return "sqrt_price_reference"
	}
	s.SqrtPriceReference = u128At(data, o)
	if o = base + 32; o+16 > len(data) {
		return "volatility_accumulator"
	}
	s.VolatilityAccumulator = u128At(data, o)
	if o = base + 48; o+16 > len(data) {
		return "volatility_reference"
	}
	s.VolatilityReference = u128At(data, o)
	return ""
}

type MeteoraDbcPoolMetrics struct {
	TotalProtocolBaseFee  uint64 // offset 0
	TotalProtocolQuoteFee uint64 // offset 8
	TotalTradingBaseFee   uint64 // offset 16
	TotalTradingQuoteFee  uint64 // offset 24
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *MeteoraDbcPoolMetrics) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+8 > len(data) {
		return "total_protocol_base_fee"
	}
	s.TotalProtocolBaseFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 8; o+8 > len(data) {
		return "total_protocol_quote_fee"
	}
	s.TotalProtocolQuoteFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 16; o+8 > len(data) {
		return "total_trading_base_fee"
	}
	s.TotalTradingBaseFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 24; o+8 > len(data) {
		return "total_trading_quote_fee"
	}
	s.TotalTradingQuoteFee = binary.LittleEndian.Uint64(data[o:])
	return ""
}

type MeteoraDbcPoolConfig struct {
	QuoteMint                     Pubkey                                    // offset 0
	FeeClaimer                    Pubkey                                    // offset 32
	LeftoverReceiver              Pubkey                                    // offset 64
	PoolFees                      MeteoraDbcPoolFeesConfig                  // offset 96
	CollectFeeMode                uint8                                     // offset 224
	MigrationOption               uint8                                     // offset 225
	ActivationType                uint8                                     // offset 226
	TokenDecimal                  uint8                                     // offset 227
	Version                       uint8                                     // offset 228
	TokenType                     uint8                                     // offset 229
	QuoteTokenFlag                uint8                                     // offset 230
	PartnerLockedLpPercentage     uint8                                     // offset 231
	PartnerLpPercentage           uint8                                     // offset 232
	CreatorLockedLpPercentage     uint8                                     // offset 233
	CreatorLpPercentage           uint8                                     // offset 234
	MigrationFeeOption            uint8                                     // offset 235
	FixedTokenSupplyFlag          uint8                                     // offset 236
	CreatorTradingFeePercentage   uint8                                     // offset 237
	TokenUpdateAuthority          uint8                                     // offset 238
	MigrationFeePercentage        uint8                                     // offset 239
	CreatorMigrationFeePercentage uint8                                     // offset 240
	Padding0                      [7]uint8                                  // offset 241
	SwapBaseAmount                uint64                                    // offset 248
	MigrationQuoteThreshold       uint64                                    // offset 256
	MigrationBaseThreshold        uint64                                    // offset 264
	MigrationSqrtPrice            U128                                      // offset 272
	LockedVestingConfig           MeteoraDbcLockedVestingConfig             // offset 288
	PreMigrationTokenSupply       uint64                                    // offset 336
	PostMigrationTokenSupply      uint64                                    // offset 344
	MigratedCollectFeeMode        uint8                                     // offset 352
	MigratedDynamicFee            uint8                                     // offset 353
	MigratedPoolFeeBps            uint16                                    // offset 354
	Padding1                      [12]uint8                                 // offset 356
	Padding2                      U128                                      // offset 368
	SqrtStartPrice                U128                                      // offset 384
	Curve                         [20]MeteoraDbcLiquidityDistributionConfig // offset 400
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *MeteoraDbcPoolConfig) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+32 > len(data) {
		return "quote_mint"
	}
	s.QuoteMint = pubkeyAt(data, o)
	if o = base + 32; o+32 > len(data) {
		return "fee_claimer"
	}
	s.FeeClaimer = pubkeyAt(data, o)
	if o = base + 64; o+32 > len(data) {
		return "leftover_receiver"
	}
	s.LeftoverReceiver = pubkeyAt(data, o)
	if o = base + 96; o+128 > len(data) {
		return "pool_fees"
	}
	s.PoolFees.decodeAt(data, o)
	if o = base + 224; o+1 > len(data) {
		return "collect_fee_mode"
	}
	s.CollectFeeMode = data[o]
	if o = base + 225; o+1 > len(data) {
		return "migration_option"
	}
	s.MigrationOption = data[o]
	if o = base + 226; o+1 > len(data) {
		return "activation_type"
	}
	s.ActivationType = data[o]
	if o = base + 227; o+1 > len(data) {
		return "token_decimal"
	}
	s.TokenDecimal = data[o]
	if o = base + 228; o+1 > len(data) {
		return "version"
	}
	s.Version = data[o]
	if o = base + 229; o+1 > len(data) {
		return "token_type"
	}
	s.TokenType = data[o]
	if o = base + 230; o+1 > len(data) {
		return "quote_token_flag"
	}
	s.QuoteTokenFlag = data[o]
	if o = base + 231; o+1 > len(data) {
		return "partner_locked_lp_percentage"
	}
	s.PartnerLockedLpPercentage = data[o]
	if o = base + 232; o+1 > len(data) {
		return "partner_lp_percentage"
	}
	s.PartnerLpPercentage = data[o]
	if o = base + 233; o+1 > len(data) {
		return "creator_locked_lp_percentage"
	}
	s.CreatorLockedLpPercentage = data[o]
	if o = base + 234; o+1 > len(data) {
		return "creator_lp_percentage"
	}
	s.CreatorLpPercentage = data[o]
	if o = base + 235; o+1 > len(data) {
		return "migration_fee_option"
	}
	s.MigrationFeeOption = data[o]
	if o = base + 236; o+1 > len(data) {
		return "fixed_token_supply_flag"
	}
	s.FixedTokenSupplyFlag = data[o]
	if o = base + 237; o+1 > len(data) {
		return "creator_trading_fee_percentage"
	}
	s.CreatorTradingFeePercentage = data[o]
	if o = base + 238; o+1 > len(data) {
		return "token_update_authority"
	}
	s.TokenUpdateAuthority = data[o]
	if o = base + 239; o+1 > len(data) {
		return "migration_fee_percentage"
	}
	s.MigrationFeePercentage = data[o]
	if o = base + 240; o+1 > len(data) {
		return "creator_migration_fee_percentage"
	}
	s.CreatorMigrationFeePercentage = data[o]
	if o = base + 241; o+7 > len(data) {
		return "_padding_0"
	}
	for i := 0; i < 7; i++ {
		o = base + 241 + i*1
		s.Padding0[i] = data[o]
	}
	if o = base + 248; o+8 > len(data) {
		return "swap_base_amount"
	}
	s.SwapBaseAmount = binary.LittleEndian.Uint64(data[o:])
	if o = base + 256; o+8 > len(data) {
		return "migration_quote_threshold"
	}
	s.MigrationQuoteThreshold = binary.LittleEndian.Uint64(data[o:])
	if o = base + 264; o+8 > len(data) {
		return "migration_base_threshold"
	}
	s.MigrationBaseThreshold = binary.LittleEndian.Uint64(data[o:])
	if o = base + 272; o+16 > len(data) {
		return "migration_sqrt_price"
	}
	s.MigrationSqrtPrice = u128At(data, o)
	if o = base + 288; o+48 > len(data) {
		return "locked_vesting_config"
	}
	s.LockedVestingConfig.decodeAt(data, o)
	if o = base + 336; o+8 > len(data) {
		return "pre_migration_token_supply"
	}
	s.PreMigrationTokenSupply = binary.LittleEndian.Uint64(data[o:])
	if o = base + 344; o+8 > len(data) {
		return "post_migration_token_supply"
	}
	s.PostMigrationTokenSupply = binary.LittleEndian.Uint64(data[o:])
	if o = base + 352; o+1 > len(data) {
		return "migrated_collect_fee_mode"
	}
	s.MigratedCollectFeeMode = data[o]
	if o = base + 353; o+1 > len(data) {
		return "migrated_dynamic_fee"
	}
	s.MigratedDynamicFee = data[o]
	if o = base + 354; o+2 > len(data) {
		return "migrated_pool_fee_bps"
	}
	s.MigratedPoolFeeBps = binary.LittleEndian.Uint16(data[o:])
	if o = base + 356; o+12 > len(data) {
		return "_padding_1"
	}
	for i := 0; i < 12; i++ {
		o = base + 356 + i*1
		s.Padding1[i] = data[o]
	}
	if o = base + 368; o+16 > len(data) {
		return "_padding_2"
	}
	s.Padding2 = u128At(data, o)
	if o = base + 384; o+16 > len(data) {
		return "sqrt_start_price"
	}
	s.SqrtStartPrice = u128At(data, o)
	if o = base + 400; o+640 > len(data) {
		return "curve"
	}
	for i := 0; i < 20; i++ {
		o = base + 400 + i*32
		s.Curve[i].decodeAt(data, o)
	}
	return ""
}

type MeteoraDbcPoolFeesConfig struct {
	BaseFee            MeteoraDbcBaseFeeConfig    // offset 0
	DynamicFee         MeteoraDbcDynamicFeeConfig // offset 32
	Padding0           [5]uint64                  // offset 80
	Padding1           [6]uint8                   // offset 120
	ProtocolFeePercent uint8                      // offset 126
	ReferralFeePercent uint8                      // offset 127
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *MeteoraDbcPoolFeesConfig) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+32 > len(data) {
		return "base_fee"
	}
	s.BaseFee.decodeAt(data, o)
	if o = base + 32; o+48 > len(data) {
		return "dynamic_fee"
	}
	s.DynamicFee.decodeAt(data, o)
	if o = base + 80; o+40 > len(data) {
		return "padding_0"
	}
	for i := 0; i < 5; i++ {
		o = base + 80 + i*8
		s.Padding0[i] = binary.LittleEndian.Uint64(data[o:])
	}
	if o = base + 120; o+6 > len(data) {
		return "padding_1"
	}
	for i := 0; i < 6; i++ {
		o = base + 120 + i*1
		s.Padding1[i] = data[o]
	}
	if o = base + 126; o+1 > len(data) {
		return "protocol_fee_percent"
	}
	s.ProtocolFeePercent = data[o]
	if o = base + 127; o+1 > len(data) {
		return "referral_fee_percent"
	}
	s.ReferralFeePercent = data[o]
	return ""
}

type MeteoraDbcBaseFeeConfig struct {
	CliffFeeNumerator uint64   // offset 0
	SecondFactor      uint64   // offset 8
	ThirdFactor       uint64   // offset 16
	FirstFactor       uint16   // offset 24
	BaseFeeMode       uint8    // offset 26
	Padding0          [5]uint8 // offset 27
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *MeteoraDbcBaseFeeConfig) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+8 > len(data) {
		return "cliff_fee_numerator"
	}
	s.CliffFeeNumerator = binary.LittleEndian.Uint64(data[o:])
	if o = base + 8; o+8 > len(data) {
		return "second_factor"
	}
	s.SecondFactor = binary.LittleEndian.Uint64(data[o:])
	if o = base + 16; o+8 > len(data) {
		return "third_factor"
	}
	s.ThirdFactor = binary.LittleEndian.Uint64(data[o:])
	if o = base + 24; o+2 > len(data) {
		return "first_factor"
	}
	s.FirstFactor = binary.LittleEndian.Uint16(data[o:])
	if o = base + 26; o+1 > len(data) {
		return "base_fee_mode"
	}
	s.BaseFeeMode = data[o]
	if o = base + 27; o+5 > len(data) {
		return "padding_0"
	}
	for i := 0; i < 5; i++ {
		o = base + 27 + i*1
		s.Padding0[i] = data[o]
	}
	return ""
}

type MeteoraDbcDynamicFeeConfig struct {
	Initialized              uint8    // offset 0
	Padding                  [7]uint8 // offset 1
	MaxVolatilityAccumulator uint32   // offset 8
	VariableFeeControl       uint32   // offset 12
	BinStep                  uint16   // offset 16
	FilterPeriod             uint16   // offset 18
	DecayPeriod              uint16   // offset 20
	ReductionFactor          uint16   // offset 22
	Padding2                 [8]uint8 // offset 24
	BinStepU128              U128     // offset 32
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *MeteoraDbcDynamicFeeConfig) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+1 > len(data) {
		return "initialized"
	}
	s.Initialized = data[o]
	if o = base + 1; o+7 > len(data) {
		return "padding"
	}
	for i := 0; i < 7; i++ {
		o = base + 1 + i*1
		s.Padding[i] = data[o]
	}
	if o = base + 8; o+4 > len(data) {
		return "max_volatility_accumulator"
	}
	s.MaxVolatilityAccumulator = binary.LittleEndian.Uint32(data[o:])
	if o = base + 12; o+4 > len(data) {
		return "variable_fee_control"
	}
	s.VariableFeeControl = binary.LittleEndian.Uint32(data[o:])
	if o = base + 16; o+2 > len(data) {
		return "bin_step"
	}
	s.BinStep = binary.LittleEndian.Uint16(data[o:])
	if o = base + 18; o+2 > len(data) {
		return "filter_period"
	}
	s.FilterPeriod = binary.LittleEndian.Uint16(data[o:])
	if o = base + 20; o+2 > len(data) {
		return "decay_period"
	}
	s.DecayPeriod = binary.LittleEndian.Uint16(data[o:])
	if o = base + 22; o+2 > len(data) {
		return "reduction_factor"
	}
	s.ReductionFactor = binary.LittleEndian.Uint16(data[o:])
	if o = base + 24; o+8 > len(data) {
		return "padding2"
	}
	for i := 0; i < 8; i++ {
		o = base + 24 + i*1
		s.Padding2[i] = data[o]
	}
	if o = base + 32; o+16 > len(data) {
		return "bin_step_u128"
	}
	s.BinStepU128 = u128At(data, o)
	return ""
}

type MeteoraDbcLockedVestingConfig struct {
	AmountPerPeriod                uint64 // offset 0
	CliffDurationFromMigrationTime uint64 // offset 8
	Frequency                      uint64 // offset 16
	NumberOfPeriod                 uint64 // offset 24
	CliffUnlockAmount              uint64 // offset 32
	Padding                        uint64 // offset 40
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *MeteoraDbcLockedVestingConfig) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+8 > len(data) {
		return "amount_per_period"
	}
	s.AmountPerPeriod = binary.LittleEndian.Uint64(data[o:])
	if o = base + 8; o+8 > len(data) {
		return "cliff_duration_from_migration_time"
	}
	s.CliffDurationFromMigrationTime = binary.LittleEndian.Uint64(data[o:])
	if o = base + 16; o+8 > len(data) {
		return "frequency"
	}
	s.Frequency = binary.LittleEndian.Uint64(data[o:])
	if o = base + 24; o+8 > len(data) {
		return "number_of_period"
	}
	s.NumberOfPeriod = binary.LittleEndian.Uint64(data[o:])
	if o = base + 32; o+8 > len(data) {
		return "cliff_unlock_amount"
	}
	s.CliffUnlockAmount = binary.LittleEndian.Uint64(data[o:])
	if o = base + 40; o+8 > len(data) {
		return "_padding"
	}
	s.Padding = binary.LittleEndian.Uint64(data[o:])
	return ""
}

type MeteoraDbcLiquidityDistributionConfig struct {
	SqrtPrice U128 // offset 0
	Liquidity U128 // offset 16
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *MeteoraDbcLiquidityDistributionConfig) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+16 > len(data) {
		return "sqrt_price"
	}
	s.SqrtPrice = u128At(data, o)
	if o = base + 16; o+16 > len(data) {
		return "liquidity"
	}
	s.Liquidity = u128At(data, o)
	return ""
}

type MoonitCurveAccount struct {
	TotalSupply        uint64 // offset 0
	CurveAmount        uint64 // offset 8
	Mint               Pubkey // offset 16
	Decimals           uint8  // offset 48
	CollateralCurrency uint8  // offset 49
	CurveType          uint8  // offset 50
	MarketcapThreshold uint64 // offset 51
	MarketcapCurrency  uint8  // offset 59
	MigrationFee       uint64 // offset 60
	CoefB              uint32 // offset 68
	Bump               uint8  // offset 72
	MigrationTarget    uint8  // offset 73
	PriceIncrease      uint16 // offset 74
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *MoonitCurveAccount) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+8 > len(data) {
		return "total_supply"
	}
	s.TotalSupply = binary.LittleEndian.Uint64(data[o:])
	if o = base + 8; o+8 > len(data) {
		return "curve_amount"
	}
	s.CurveAmount = binary.LittleEndian.Uint64(data[o:])
	if o = base + 16; o+32 > len(data) {
		return "mint"
	}
	s.Mint = pubkeyAt(data, o)
	if o = base + 48; o+1 > len(data) {
		return "decimals"
	}
	s.Decimals = data[o]
	if o = base + 49; o+1 > len(data) {
		return "collateral_currency"
	}
	s.CollateralCurrency = data[o]
	if o = base + 50; o+1 > len(data) {
		return "curve_type"
	}
	s.CurveType = data[o]
	if o = base + 51; o+8 > len(data) {
		return "marketcap_threshold"
	}
	s.MarketcapThreshold = binary.LittleEndian.Uint64(data[o:])
	if o = base + 59; o+1 > len(data) {
		return "marketcap_currency"
	}
	s.MarketcapCurrency = data[o]
	if o = base + 60; o+8 > len(data) {
		return "migration_fee"
	}
	s.MigrationFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 68; o+4 > len(data) {
		return "coef_b"
	}
	s.CoefB = binary.LittleEndian.Uint32(data[o:])
	if o = base + 72; o+1 > len(data) {
		return "bump"
	}
	s.Bump = data[o]
	if o = base + 73; o+1 > len(data) {
		return "migration_target"
	}
	s.MigrationTarget = data[o]
	if o = base + 74; o+2 > len(data) {
		return "price_increase"
	}
	s.PriceIncrease = binary.LittleEndian.Uint16(data[o:])
	return ""
}

type MoonitConfigAccount struct {
	MigrationAuthority             Pubkey // offset 0
	BackendAuthority               Pubkey // offset 32
	ConfigAuthority                Pubkey // offset 64
	HelioFee                       Pubkey // offset 96
	DexFee                         Pubkey // offset 128
	FeeBps                         uint16 // offset 160
	DexFeeShare                    uint8  // offset 162
	MigrationFee                   uint64 // offset 163
	LinearCurveMcapThreshold       uint64 // offset 171
	MarketcapCurrency              uint8  // offset 179
	MinSupportedDecimalPlaces      uint8  // offset 180
	MaxSupportedDecimalPlaces      uint8  // offset 181
	MinSupportedTokenSupply        uint64 // offset 182
	MaxSupportedTokenSupply        uint64 // offset 190
	Bump                           uint8  // offset 198
	CoefB                          uint32 // offset 199
	ConstantProductV1McapThreshold uint64 // offset 203
	ConstantProductV2McapThreshold uint64 // offset 211
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *MoonitConfigAccount) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+32 > len(data) {
		return "migration_authority"
	}
	s.MigrationAuthority = pubkeyAt(data, o)
	if o = base + 32; o+32 > len(data) {
		return "backend_authority"
	}
	s.BackendAuthority = pubkeyAt(data, o)
	if o = base + 64; o+32 > len(data) {
		return "config_authority"
	}
	s.ConfigAuthority = pubkeyAt(data, o)
	if o = base + 96; o+32 > len(data) {
		return "helio_fee"
	}
	s.HelioFee = pubkeyAt(data, o)
	if o = base + 128; o+32 > len(data) {
		return "dex_fee"
	}
	s.DexFee = pubkeyAt(data, o)
	if o = base + 160; o+2 > len(data) {
		return "fee_bps"
	}
	s.FeeBps = binary.LittleEndian.Uint16(data[o:])
	if o = base + 162; o+1 > len(data) {
		return "dex_fee_share"
	}
	s.DexFeeShare = data[o]
	if o = base + 163; o+8 > len(data) {
		return "migration_fee"
	}
	s.MigrationFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 171; o+8 > len(data) {
		return "linear_curve_mcap_threshold"
	}
	s.LinearCurveMcapThreshold = binary.LittleEndian.Uint64(data[o:])
	if o = base + 179; o+1 > len(data) {
		return "marketcap_currency"
	}
	s.MarketcapCurrency = data[o]
	if o = base + 180; o+1 > len(data) {
		return "min_supported_decimal_places"
	}
	s.MinSupportedDecimalPlaces = data[o]
	if o = base + 181; o+1 > len(data) {
		return "max_supported_decimal_places"
	}
	s.MaxSupportedDecimalPlaces = data[o]
	if o = base + 182; o+8 > len(data) {
		return "min_supported_token_supply"
	}
	s.MinSupportedTokenSupply = binary.LittleEndian.Uint64(data[o:])
	if o = base + 190; o+8 > len(data) {
		return "max_supported_token_supply"
	}
	s.MaxSupportedTokenSupply = binary.LittleEndian.Uint64(data[o:])
	if o = base + 198; o+1 > len(data) {
		return "bump"
	}
	s.Bump = data[o]
	if o = base + 199; o+4 > len(data) {
		return "coef_b"
	}
	s.CoefB = binary.LittleEndian.Uint32(data[o:])
	if o = base + 203; o+8 > len(data) {
		return "constant_product_v1_mcap_threshold"
	}
	s.ConstantProductV1McapThreshold = binary.LittleEndian.Uint64(data[o:])
	if o = base + 211; o+8 > len(data) {
		return "constant_product_v2_mcap_threshold"
	}
	s.ConstantProductV2McapThreshold = binary.LittleEndian.Uint64(data[o:])
	return ""
}

type HeavenLiquidityPoolState struct {
	BaseTokenMint                  Pubkey    // offset 0
	BaseTokenMintDecimals          uint8     // offset 32
	BaseTokenVault                 Pubkey    // offset 33
	BaseTokenSwapTaxVault          Pubkey    // offset 65
	QuoteTokenMint                 Pubkey    // offset 97
	QuoteTokenMintDecimals         uint8     // offset 129
	QuoteTokenVault                Pubkey    // offset 130
	QuoteTokenSwapTaxVault         Pubkey    // offset 162
	ProtocolBaseTokenSwapFeeVault  Pubkey    // offset 194
	ProtocolQuoteTokenSwapFeeVault Pubkey    // offset 226
	LPTokenMint                    Pubkey    // offset 258
	LPTokenMintDecimals            uint8     // offset 290
	LPTokenCurrentSupply           uint64    // offset 291
	SwapFeeNumerator               uint64    // offset 299
	SwapFeeDenominator             uint64    // offset 307
	ProtocolSwapFeeNumerator       uint64    // offset 315
	ProtocolSwapFeeDenominator     uint64    // offset 323
	BuyTax                         uint64    // offset 331
	SellTax                        uint64    // offset 339
	ProtocolTaxNumerator           uint64    // offset 347
	ProtocolTaxDenominator         uint64    // offset 355
	Creator                        Pubkey    // offset 363
	AuthorityBump                  uint8     // offset 395
	AllowSwap                      bool      // offset 396
	AllowRemoveLiquidity           bool      // offset 397
	AllowAddLiquidity              bool      // offset 398
	OpenAt                         uint64    // offset 399
	CreatedAt                      uint64    // offset 407
	LockUntil                      uint64    // offset 415
	ProtocolConfigVersion          uint16    // offset 423
	TaxationMode                   uint8     // offset 425
	SwapBaseInAmount               U128      // offset 426
	SwapQuoteInAmount              U128      // offset 442
	SwapBaseOutAmount              U128      // offset 458
	SwapQuoteOutAmount             U128      // offset 474
	SwapBaseFee                    U128      // offset 490
	SwapQuoteFee                   U128      // offset 506
	SwapBaseToQuoteCount           U128      // offset 522
	SwapQuoteToBaseCount           U128      // offset 538
	SwapInCount                    U128      // offset 554
	SwapOutCount                   U128      // offset 570
	BaseSwapTaxAmount              U128      // offset 586
	QuoteSwapTaxAmount             U128      // offset 602
	FirstSwapOutTimestamp          uint64    // offset 618
	LatestSwapOutTimestamp         uint64    // offset 626
	FirstSwapInTimestamp           uint64    // offset 634
	LatestSwapInTimestamp          uint64    // offset 642
	FirstBaseToQuoteAmount         U128      // offset 650
	LatestBaseToQuoteAmount        U128      // offset 666
	FirstQuoteToBaseAmount         U128      // offset 682
	LatestQuoteToBaseAmount        U128      // offset 698
	LockedLp                       uint64    // offset 714
	InitialLp                      uint64    // offset 722
	LiquidityAdded                 U128      // offset 730
	LiquidityRemoved               U128      // offset 746
	IsInitialLpBurned              bool      // offset 762
	BaseTokenAdded                 U128      // offset 763
	BaseTokenRemoved               U128      // offset 779
	QuoteTokenAdded                U128      // offset 795
	QuoteTokenRemoved              U128      // offset 811
	BaseProtocolTax                U128      // offset 827
	QuoteProtocolTax               U128      // offset 843
	BaseProtocolFee                U128      // offset 859
	QuoteProtocolFee               U128      // offset 875
	BaseTokenVaultBalance          uint64    // offset 891
	QuoteTokenVaultBalance         uint64    // offset 899
	MinPrice                       float64   // offset 907
	MaxPrice                       float64   // offset 915
	CurrPrice                      float64   // offset 923
	CurrMc                         float64   // offset 931
	MinMc                          float64   // offset 939
	MaxMc                          float64   // offset 947
	LockedTaxation                 bool      // offset 955
	DisableNonCreatorAddLiquidity  bool      // offset 956
	AllowCreatorClaimSwapFee       bool      // offset 957
	WhitelistConfig                [8]uint8  // offset 958
	BaseTokenProgram               Pubkey    // offset 966
	QuoteTokenProgram              Pubkey    // offset 998
	AllowSameSlotTrading           bool      // offset 1030
	EnableSandwichAttackMitigation bool      // offset 1031
	InitialBaseTokenVaultBalance   uint64    // offset 1032
	InitialQuoteTokenVaultBalance  uint64    // offset 1040
	IsSimplePool                   bool      // offset 1048
	CreatedAtSlot                  uint64    // offset 1049
	SnapshotSlot                   uint64    // offset 1057
	SnapshotBaseTokenVaultBalance  uint64    // offset 1065
	SnapshotQuoteTokenVaultBalance uint64    // offset 1073
	Padding                        [32]uint8 // offset 1081
	Padding2                       [32]uint8 // offset 1113
	Padding3                       [32]uint8 // offset 1145
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *HeavenLiquidityPoolState) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+32 > len(data) {
		return "base_token_mint"
	}
	s.BaseTokenMint = pubkeyAt(data, o)
	if o = base + 32; o+1 > len(data) {
		return "base_token_mint_decimals"
	}
	s.BaseTokenMintDecimals = data[o]
	if o = base + 33; o+32 > len(data) {
		return "base_token_vault"
	}
	s.BaseTokenVault = pubkeyAt(data, o)
	if o = base + 65; o+32 > len(data) {
		return "base_token_swap_tax_vault"
	}
	s.BaseTokenSwapTaxVault = pubkeyAt(data, o)
	if o = base + 97; o+32 > len(data) {
		return "quote_token_mint"
	}
	s.QuoteTokenMint = pubkeyAt(data, o)
	if o = base + 129; o+1 > len(data) {
		return "quote_token_mint_decimals"
	}
	s.QuoteTokenMintDecimals = data[o]
	if o = base + 130; o+32 > len(data) {
		return "quote_token_vault"
	}
	s.QuoteTokenVault = pubkeyAt(data, o)
	if o = base + 162; o+32 > len(data) {
		return "quote_token_swap_tax_vault"
	}
	s.QuoteTokenSwapTaxVault = pubkeyAt(data, o)
	if o = base + 194; o+32 > len(data) {
		return "protocol_base_token_swap_fee_vault"
	}
	s.ProtocolBaseTokenSwapFeeVault = pubkeyAt(data, o)
	if o = base + 226; o+32 > len(data) {
		return "protocol_quote_token_swap_fee_vault"
	}
	s.ProtocolQuoteTokenSwapFeeVault = pubkeyAt(data, o)
	if o = base + 258; o+32 > len(data) {
		return "lp_token_mint"
	}
	s.LPTokenMint = pubkeyAt(data, o)
	if o = base + 290; o+1 > len(data) {
		return "lp_token_mint_decimals"
	}
	s.LPTokenMintDecimals = data[o]
	if o = base + 291; o+8 > len(data) {
		return "lp_token_current_supply"
	}
	s.LPTokenCurrentSupply = binary.LittleEndian.Uint64(data[o:])
	if o = base + 299; o+8 > len(data) {
		return "swap_fee_numerator"
	}
	s.SwapFeeNumerator = binary.LittleEndian.Uint64(data[o:])
	if o = base + 307; o+8 > len(data) {
		return "swap_fee_denominator"
	}
	s.SwapFeeDenominator = binary.LittleEndian.Uint64(data[o:])
	if o = base + 315; o+8 > len(data) {
		return "protocol_swap_fee_numerator"
	}
	s.ProtocolSwapFeeNumerator = binary.LittleEndian.Uint64(data[o:])
	if o = base + 323; o+8 > len(data) {
		return "protocol_swap_fee_denominator"
	}
	s.ProtocolSwapFeeDenominator = binary.LittleEndian.Uint64(data[o:])
	if o = base + 331; o+8 > len(data) {
		return "buy_tax"
	}
	s.BuyTax = binary.LittleEndian.Uint64(data[o:])
	if o = base + 339; o+8 > len(data) {
		return "sell_tax"
	}
	s.SellTax = binary.LittleEndian.Uint64(data[o:])
	if o = base + 347; o+8 > len(data) {
		return "protocol_tax_numerator"
	}
	s.ProtocolTaxNumerator = binary.LittleEndian.Uint64(data[o:])
	if o = base + 355; o+8 > len(data) {
		return "protocol_tax_denominator"
	}
	s.ProtocolTaxDenominator = binary.LittleEndian.Uint64(data[o:])
	if o = base + 363; o+32 > len(data) {
		return "creator"
	}
	s.Creator = pubkeyAt(data, o)
	if o = base + 395; o+1 > len(data) {
		return "authority_bump"
	}
	s.AuthorityBump = data[o]
	if o = base + 396; o+1 > len(data) {
		return "allow_swap"
	}
	s.AllowSwap = data[o] == 1
	if o = base + 397; o+1 > len(data) {
		return "allow_remove_liquidity"
	}
	s.AllowRemoveLiquidity = data[o] == 1
	if o = base + 398; o+1 > len(data) {
		return "allow_add_liquidity"
	}
	s.AllowAddLiquidity = data[o] == 1
	if o = base + 399; o+8 > len(data) {
		return "open_at"
	}
	s.OpenAt = binary.LittleEndian.Uint64(data[o:])
	if o = base + 407; o+8 > len(data) {
		return "created_at"
	}
	s.CreatedAt = binary.LittleEndian.Uint64(data[o:])
	if o = base + 415; o+8 > len(data) {
		return "lock_until"
	}
	s.LockUntil = binary.LittleEndian.Uint64(data[o:])
	if o = base + 423; o+2 > len(data) {
		return "protocol_config_version"
	}
	s.ProtocolConfigVersion = binary.LittleEndian.Uint16(data[o:])
	if o = base + 425; o+1 > len(data) {
		return "taxation_mode"
	}
	s.TaxationMode = data[o]
	if o = base + 426; o+16 > len(data) {
		return "swap_base_in_amount"
	}
	s.SwapBaseInAmount = u128At(data, o)
	if o = base + 442; o+16 > len(data) {
		return "swap_quote_in_amount"
	}
	s.SwapQuoteInAmount = u128At(data, o)
	if o = base + 458; o+16 > len(data) {
		return "swap_base_out_amount"
	}
	s.SwapBaseOutAmount = u128At(data, o)
	if o = base + 474; o+16 > len(data) {
		return "swap_quote_out_amount"
	}
	s.SwapQuoteOutAmount = u128At(data, o)
	if o = base + 490; o+16 > len(data) {
		return "swap_base_fee"
	}
	s.SwapBaseFee = u128At(data, o)
	if o = base + 506; o+16 > len(data) {
		return "swap_quote_fee"
	}
	s.SwapQuoteFee = u128At(data, o)
	if o = base + 522; o+16 > len(data) {
		return "swap_base_to_quote_count"
	}
	s.SwapBaseToQuoteCount = u128At(data, o)
	if o = base + 538; o+16 > len(data) {
		return "swap_quote_to_base_count"
	}
	s.SwapQuoteToBaseCount = u128At(data, o)
	if o = base + 554; o+16 > len(data) {
		return "swap_in_count"
	}
	s.SwapInCount = u128At(data, o)
	if o = base + 570; o+16 > len(data) {
		return "swap_out_count"
	}
	s.SwapOutCount = u128At(data, o)
	if o = base + 586; o+16 > len(data) {
		return "base_swap_tax_amount"
	}
	s.BaseSwapTaxAmount = u128At(data, o)
	if o = base + 602; o+16 > len(data) {
		return "quote_swap_tax_amount"
	}
	s.QuoteSwapTaxAmount = u128At(data, o)
	if o = base + 618; o+8 > len(data) {
		return "first_swap_out_timestamp"
	}
	s.FirstSwapOutTimestamp = binary.LittleEndian.Uint64(data[o:])
	if o = base + 626; o+8 > len(data) {
		return "latest_swap_out_timestamp"
	}
	s.LatestSwapOutTimestamp = binary.LittleEndian.Uint64(data[o:])
	if o = base + 634; o+8 > len(data) {
		return "first_swap_in_timestamp"
	}
	s.FirstSwapInTimestamp = binary.LittleEndian.Uint64(data[o:])
	if o = base + 642; o+8 > len(data) {
		return "latest_swap_in_timestamp"
	}
	s.LatestSwapInTimestamp = binary.LittleEndian.Uint64(data[o:])
	if o = base + 650; o+16 > len(data) {
		return "first_base_to_quote_amount"
	}
	s.FirstBaseToQuoteAmount = u128At(data, o)
	if o = base + 666; o+16 > len(data) {
		return "latest_base_to_quote_amount"
	}
	s.LatestBaseToQuoteAmount = u128At(data, o)
	if o = base + 682; o+16 > len(data) {
		return "first_quote_to_base_amount"
	}
	s.FirstQuoteToBaseAmount = u128At(data, o)
	if o = base + 698; o+16 > len(data) {
		return "latest_quote_to_base_amount"
	}
	s.LatestQuoteToBaseAmount = u128At(data, o)
	if o = base + 714; o+8 > len(data) {
		return "locked_lp"
	}
	s.LockedLp = binary.LittleEndian.Uint64(data[o:])
	if o = base + 722; o+8 > len(data) {
		return "initial_lp"
	}
	s.InitialLp = binary.LittleEndian.Uint64(data[o:])
	if o = base + 730; o+16 > len(data) {
		return "liquidity_added"
	}
	s.LiquidityAdded = u128At(data, o)
	if o = base + 746; o+16 > len(data) {
		return "liquidity_removed"
	}
	s.LiquidityRemoved = u128At(data, o)
	if o = base + 762; o+1 > len(data) {
		return "is_initial_lp_burned"
	}
	s.IsInitialLpBurned = data[o] == 1
	if o = base + 763; o+16 > len(data) {
		return "base_token_added"
	}
	s.BaseTokenAdded = u128At(data, o)
	if o = base + 779; o+16 > len(data) {
		return "base_token_removed"
	}
	s.BaseTokenRemoved = u128At(data, o)
	if o = base + 795; o+16 > len(data) {
		return "quote_token_added"
	}
	s.QuoteTokenAdded = u128At(data, o)
	if o = base + 811; o+16 > len(data) {
		return "quote_token_removed"
	}
	s.QuoteTokenRemoved = u128At(data, o)
	if o = base + 827; o+16 > len(data) {
		return "base_protocol_tax"
	}
	s.BaseProtocolTax = u128At(data, o)
	if o = base + 843; o+16 > len(data) {
		return "quote_protocol_tax"
	}
	s.QuoteProtocolTax = u128At(data, o)
	if o = base + 859; o+16 > len(data) {
		return "base_protocol_fee"
	}
	s.BaseProtocolFee = u128At(data, o)
	if o = base + 875; o+16 > len(data) {
		return "quote_protocol_fee"
	}
	s.QuoteProtocolFee = u128At(data, o)
	if o = base + 891; o+8 > len(data) {
		return "base_token_vault_balance"
	}
	s.BaseTokenVaultBalance = binary.LittleEndian.Uint64(data[o:])
	if o = base + 899; o+8 > len(data) {
		return "quote_token_vault_balance"
	}
	s.QuoteTokenVaultBalance = binary.LittleEndian.Uint64(data[o:])
	if o = base + 907; o+8 > len(data) {
		return "min_price"
	}
	s.MinPrice = math.Float64frombits(binary.LittleEndian.Uint64(data[o:]))
	if o = base + 915; o+8 > len(data) {
		return "max_price"
	}
	s.MaxPrice = math.Float64frombits(binary.LittleEndian.Uint64(data[o:]))
	if o = base + 923; o+8 > len(data) {
		return "curr_price"
	}
	s.CurrPrice = math.Float64frombits(binary.LittleEndian.Uint64(data[o:]))
	if o = base + 931; o+8 > len(data) {
		return "curr_mc"
	}
	s.CurrMc = math.Float64frombits(binary.LittleEndian.Uint64(data[o:]))
	if o = base + 939; o+8 > len(data) {
		return "min_mc"
	}
	s.MinMc = math.Float64frombits(binary.LittleEndian.Uint64(data[o:]))
	if o = base + 947; o+8 > len(data) {
		return "max_mc"
	}
	s.MaxMc = math.Float64frombits(binary.LittleEndian.Uint64(data[o:]))
	if o = base + 955; o+1 > len(data) {
		return "locked_taxation"
	}
	s.LockedTaxation = data[o] == 1
	if o = base + 956; o+1 > len(data) {
		return "disable_non_creator_add_liquidity"
	}
	s.DisableNonCreatorAddLiquidity = data[o] == 1
	if o = base + 957; o+1 > len(data) {
		return "allow_creator_claim_swap_fee"
	}
	s.AllowCreatorClaimSwapFee = data[o] == 1
	if o = base + 958; o+8 > len(data) {
		return "whitelist_config"
	}
	for i := 0; i < 8; i++ {
		o = base + 958 + i*1
		s.WhitelistConfig[i] = data[o]
	}
	if o = base + 966; o+32 > len(data) {
		return "base_token_program"
	}
	s.BaseTokenProgram = pubkeyAt(data, o)
	if o = base + 998; o+32 > len(data) {
		return "quote_token_program"
	}
	s.QuoteTokenProgram = pubkeyAt(data, o)
	if o = base + 1030; o+1 > len(data) {
		return "allow_same_slot_trading"
	}
	s.AllowSameSlotTrading = data[o] == 1
	if o = base + 1031; o+1 > len(data) {
		return "enable_sandwich_attack_mitigation"
	}
	s.EnableSandwichAttackMitigation = data[o] == 1
	if o = base + 1032; o+8 > len(data) {
		return "initial_base_token_vault_balance"
	}
	s.InitialBaseTokenVaultBalance = binary.LittleEndian.Uint64(data[o:])
	if o = base + 1040; o+8 > len(data) {
		return "initial_quote_token_vault_balance"
	}
	s.InitialQuoteTokenVaultBalance = binary.LittleEndian.Uint64(data[o:])
	if o = base + 1048; o+1 > len(data) {
		return "is_simple_pool"
	}
	s.IsSimplePool = data[o] == 1
	if o = base + 1049; o+8 > len(data) {
		return "created_at_slot"
	}
	s.CreatedAtSlot = binary.LittleEndian.Uint64(data[o:])
	if o = base + 1057; o+8 > len(data) {
		return "snapshot_slot"
	}
	s.SnapshotSlot = binary.LittleEndian.Uint64(data[o:])
	if o = base + 1065; o+8 > len(data) {
		return "snapshot_base_token_vault_balance"
	}
	s.SnapshotBaseTokenVaultBalance = binary.LittleEndian.Uint64(data[o:])
	if o = base + 1073; o+8 > len(data) {
		return "snapshot_quote_token_vault_balance"
	}
	s.SnapshotQuoteTokenVaultBalance = binary.LittleEndian.Uint64(data[o:])
	if o = base + 1081; o+32 > len(data) {
		return "padding"
	}
	for i := 0; i < 32; i++ {
		o = base + 1081 + i*1
		s.Padding[i] = data[o]
	}
	if o = base + 1113; o+32 > len(data) {
		return "padding2"
	}
	for i := 0; i < 32; i++ {
		o = base + 1113 + i*1
		s.Padding2[i] = data[o]
	}
	if o = base + 1145; o+32 > len(data) {
		return "padding3"
	}
	for i := 0; i < 32; i++ {
		o = base + 1145 + i*1
		s.Padding3[i] = data[o]
	}
	return ""
}

type HeavenProtocolConfig struct {
	ProtocolConfigStateBump    uint8  // offset 0
	AllowCreatePool            bool   // offset 1
	ProtocolSwapFeeNumerator   uint64 // offset 2
	ProtocolSwapFeeDenominator uint64 // offset 10
	SwapFeeNumerator           uint64 // offset 18
	SwapFeeDenominator         uint64 // offset 26
	ProtocolTaxNumerator       uint64 // offset 34
	ProtocolTaxDenominator     uint64 // offset 42
	CreatePoolFee              uint64 // offset 50
	ProtocolOwner              Pubkey // offset 58
	Version                    uint16 // offset 90
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *HeavenProtocolConfig) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+1 > len(data) {
		return "protocol_config_state_bump"
	}
	s.ProtocolConfigStateBump = data[o]
	if o = base + 1; o+1 > len(data) {
		return "allow_create_pool"
	}
	s.AllowCreatePool = data[o] == 1
	if o = base + 2; o+8 > len(data) {
		return "protocol_swap_fee_numerator"
	}
	s.ProtocolSwapFeeNumerator = binary.LittleEndian.Uint64(data[o:])
	if o = base + 10; o+8 > len(data) {
		return "protocol_swap_fee_denominator"
	}
	s.ProtocolSwapFeeDenominator = binary.LittleEndian.Uint64(data[o:])
	if o = base + 18; o+8 > len(data) {
		return "swap_fee_numerator"
	}
	s.SwapFeeNumerator = binary.LittleEndian.Uint64(data[o:])
	if o = base + 26; o+8 > len(data) {
		return "swap_fee_denominator"
	}
	s.SwapFeeDenominator = binary.LittleEndian.Uint64(data[o:])
	if o = base + 34; o+8 > len(data) {
		return "protocol_tax_numerator"
	}
	s.ProtocolTaxNumerator = binary.LittleEndian.Uint64(data[o:])
	if o = base + 42; o+8 > len(data) {
		return "protocol_tax_denominator"
	}
	s.ProtocolTaxDenominator = binary.LittleEndian.Uint64(data[o:])
	if o = base + 50; o+8 > len(data) {
		return "create_pool_fee"
	}
	s.CreatePoolFee = binary.LittleEndian.Uint64(data[o:])
	if o = base + 58; o+32 > len(data) {
		return "protocol_owner"
	}
	s.ProtocolOwner = pubkeyAt(data, o)
	if o = base + 90; o+2 > len(data) {
		return "version"
	}
	s.Version = binary.LittleEndian.Uint16(data[o:])
	return ""
}

type VertigoPool struct {
	Enabled        bool   // offset 0
	Owner          Pubkey // offset 1
	MintA          Pubkey // offset 33
	MintB          Pubkey // offset 65
	TokenAReserves U128   // offset 97
	TokenBReserves U128   // offset 113
	Shift          U128   // offset 129
	Royalties      uint64 // offset 145
	VertigoFees    uint64 // offset 153
	Bump           uint8  // offset 161
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *VertigoPool) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+1 > len(data) {
		return "enabled"
	}
	s.Enabled = data[o] == 1
	if o = base + 1; o+32 > len(data) {
		return "owner"
	}
	s.Owner = pubkeyAt(data, o)
	if o = base + 33; o+32 > len(data) {
		return "mint_a"
	}
	s.MintA = pubkeyAt(data, o)
	if o = base + 65; o+32 > len(data) {
		return "mint_b"
	}
	s.MintB = pubkeyAt(data, o)
	if o = base + 97; o+16 > len(data) {
		return "token_a_reserves"
	}
	s.TokenAReserves = u128At(data, o)
	if o = base + 113; o+16 > len(data) {
		return "token_b_reserves"
	}
	s.TokenBReserves = u128At(data, o)
	if o = base + 129; o+16 > len(data) {
		return "shift"
	}
	s.Shift = u128At(data, o)
	if o = base + 145; o+8 > len(data) {
		return "royalties"
	}
	s.Royalties = binary.LittleEndian.Uint64(data[o:])
	if o = base + 153; o+8 > len(data) {
		return "vertigo_fees"
	}
	s.VertigoFees = binary.LittleEndian.Uint64(data[o:])
	if o = base + 161; o+1 > len(data) {
		return "bump"
	}
	s.Bump = data[o]
	return ""
}

type GofundmemeBondingCurvePool struct {
	Bump                 uint8  // offset 0
	Admin                Pubkey // offset 1
	CrankRewardBps       uint16 // offset 33
	DefundFee            uint16 // offset 35
	TotalRaised          uint64 // offset 37
	TargetRaise          uint64 // offset 45
	TotalSupply          uint64 // offset 53
	ClaimableAmountMintA uint64 // offset 61
	ClaimableAmountMintB uint64 // offset 69
	ClaimedAmountMintA   uint64 // offset 77
	ClaimedAmountMintB   uint64 // offset 85
	TokenAMint           Pubkey // offset 93
	TokenBMint           Pubkey // offset 125
	CurrentRecordNumber  uint64 // offset 157
	Whirlpool            Pubkey // offset 165
	Position             Pubkey // offset 197
	KycNetworkKey        Pubkey // offset 229
	PoolType             uint8  // offset 261
	RaiseType            uint8  // offset 262
	PoolStatus           uint8  // offset 263
}

// decodeAt fills s from data starting at base, and returns the name of
// the first field the buffer was too short to reach ("" if complete).
func (s *GofundmemeBondingCurvePool) decodeAt(data []byte, base int) string {
	var o int
	_ = o
	if o = base + 0; o+1 > len(data) {
		return "bump"
	}
	s.Bump = data[o]
	if o = base + 1; o+32 > len(data) {
		return "admin"
	}
	s.Admin = pubkeyAt(data, o)
	if o = base + 33; o+2 > len(data) {
		return "crank_reward_bps"
	}
	s.CrankRewardBps = binary.LittleEndian.Uint16(data[o:])
	if o = base + 35; o+2 > len(data) {
		return "defund_fee"
	}
	s.DefundFee = binary.LittleEndian.Uint16(data[o:])
	if o = base + 37; o+8 > len(data) {
		return "total_raised"
	}
	s.TotalRaised = binary.LittleEndian.Uint64(data[o:])
	if o = base + 45; o+8 > len(data) {
		return "target_raise"
	}
	s.TargetRaise = binary.LittleEndian.Uint64(data[o:])
	if o = base + 53; o+8 > len(data) {
		return "total_supply"
	}
	s.TotalSupply = binary.LittleEndian.Uint64(data[o:])
	if o = base + 61; o+8 > len(data) {
		return "claimable_amount_mint_a"
	}
	s.ClaimableAmountMintA = binary.LittleEndian.Uint64(data[o:])
	if o = base + 69; o+8 > len(data) {
		return "claimable_amount_mint_b"
	}
	s.ClaimableAmountMintB = binary.LittleEndian.Uint64(data[o:])
	if o = base + 77; o+8 > len(data) {
		return "claimed_amount_mint_a"
	}
	s.ClaimedAmountMintA = binary.LittleEndian.Uint64(data[o:])
	if o = base + 85; o+8 > len(data) {
		return "claimed_amount_mint_b"
	}
	s.ClaimedAmountMintB = binary.LittleEndian.Uint64(data[o:])
	if o = base + 93; o+32 > len(data) {
		return "token_a_mint"
	}
	s.TokenAMint = pubkeyAt(data, o)
	if o = base + 125; o+32 > len(data) {
		return "token_b_mint"
	}
	s.TokenBMint = pubkeyAt(data, o)
	if o = base + 157; o+8 > len(data) {
		return "current_record_number"
	}
	s.CurrentRecordNumber = binary.LittleEndian.Uint64(data[o:])
	if o = base + 165; o+32 > len(data) {
		return "whirlpool"
	}
	s.Whirlpool = pubkeyAt(data, o)
	if o = base + 197; o+32 > len(data) {
		return "position"
	}
	s.Position = pubkeyAt(data, o)
	if o = base + 229; o+32 > len(data) {
		return "kyc_network_key"
	}
	s.KycNetworkKey = pubkeyAt(data, o)
	if o = base + 261; o+1 > len(data) {
		return "pool_type"
	}
	s.PoolType = data[o]
	if o = base + 262; o+1 > len(data) {
		return "raise_type"
	}
	s.RaiseType = data[o]
	if o = base + 263; o+1 > len(data) {
		return "pool_status"
	}
	s.PoolStatus = data[o]
	return ""
}

// Discriminators, as the programs write them.
//
// These are NOT globally unique. Anchor derives them from the struct name
// alone, so every program with a `GlobalConfig` or a `Pool` shares the same
// eight bytes -- PumpSwap and Raydium LaunchLab genuinely collide here, as do
// PumpSwap and Vertigo. An account can only be identified by the pair
// (owning program, discriminator), which is what accountRegistry keys on.
var (
	DiscPumpfunBondingCurve            = [8]byte{23, 183, 248, 55, 96, 216, 172, 96}
	DiscPumpfunGlobal                  = [8]byte{167, 232, 232, 177, 200, 108, 114, 127}
	DiscPumpswapPool                   = [8]byte{241, 154, 109, 4, 17, 177, 109, 188}
	DiscPumpswapGlobalConfig           = [8]byte{149, 8, 156, 202, 160, 252, 176, 217}
	DiscRaydiumLaunchlabPoolState      = [8]byte{247, 237, 227, 245, 215, 195, 222, 70}
	DiscRaydiumLaunchlabGlobalConfig   = [8]byte{149, 8, 156, 202, 160, 252, 176, 217}
	DiscRaydiumLaunchlabPlatformConfig = [8]byte{160, 78, 128, 0, 248, 83, 230, 160}
	DiscMeteoraDbcVirtualPool          = [8]byte{213, 224, 5, 209, 98, 69, 119, 92}
	DiscMeteoraDbcPoolConfig           = [8]byte{26, 108, 14, 123, 116, 230, 129, 43}
	DiscMoonitCurveAccount             = [8]byte{8, 91, 83, 28, 132, 216, 248, 22}
	DiscMoonitConfigAccount            = [8]byte{189, 255, 97, 70, 186, 189, 24, 102}
	DiscHeavenLiquidityPoolState       = [8]byte{79, 165, 94, 63, 88, 55, 59, 174}
	DiscHeavenProtocolConfig           = [8]byte{1, 114, 119, 183, 110, 180, 30, 142}
	DiscVertigoPool                    = [8]byte{241, 154, 109, 4, 17, 177, 109, 188}
	DiscGofundmemeBondingCurvePool     = [8]byte{167, 155, 150, 227, 65, 117, 3, 86}
)

type accountKey struct {
	program string
	disc    [8]byte
}

// accountRegistry resolves (program, discriminator) to an account type.
var accountRegistry = map[accountKey]AccountKind{
	{"6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P", [8]byte{23, 183, 248, 55, 96, 216, 172, 96}}:     KindPumpfunBondingCurve,
	{"6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P", [8]byte{167, 232, 232, 177, 200, 108, 114, 127}}: KindPumpfunGlobal,
	{"pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA", [8]byte{241, 154, 109, 4, 17, 177, 109, 188}}:    KindPumpswapPool,
	{"pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA", [8]byte{149, 8, 156, 202, 160, 252, 176, 217}}:   KindPumpswapGlobalConfig,
	{"LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj", [8]byte{247, 237, 227, 245, 215, 195, 222, 70}}:  KindRaydiumLaunchlabPoolState,
	{"LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj", [8]byte{149, 8, 156, 202, 160, 252, 176, 217}}:   KindRaydiumLaunchlabGlobalConfig,
	{"LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj", [8]byte{160, 78, 128, 0, 248, 83, 230, 160}}:     KindRaydiumLaunchlabPlatformConfig,
	{"dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN", [8]byte{213, 224, 5, 209, 98, 69, 119, 92}}:      KindMeteoraDbcVirtualPool,
	{"dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN", [8]byte{26, 108, 14, 123, 116, 230, 129, 43}}:    KindMeteoraDbcPoolConfig,
	{"MoonCVVNZFSYkqNXP6bxHLPL6QQJiMagDL3qcqUQTrG", [8]byte{8, 91, 83, 28, 132, 216, 248, 22}}:       KindMoonitCurveAccount,
	{"MoonCVVNZFSYkqNXP6bxHLPL6QQJiMagDL3qcqUQTrG", [8]byte{189, 255, 97, 70, 186, 189, 24, 102}}:    KindMoonitConfigAccount,
	{"HEAVEnMX7RoaYCucpyFterLWzFJR8Ah26oNSnqBs5Jtn", [8]byte{79, 165, 94, 63, 88, 55, 59, 174}}:      KindHeavenLiquidityPoolState,
	{"HEAVEnMX7RoaYCucpyFterLWzFJR8Ah26oNSnqBs5Jtn", [8]byte{1, 114, 119, 183, 110, 180, 30, 142}}:   KindHeavenProtocolConfig,
	{"vrTGoBuy5rYSxAfV3jaRJWHH6nN9WK4NRExGxsk1bCJ", [8]byte{241, 154, 109, 4, 17, 177, 109, 188}}:    KindVertigoPool,
	{"GFMioXjhuDWMEBtuaoaDPJFPEnL2yDHCWKoVPhj1MeA7", [8]byte{167, 155, 150, 227, 65, 117, 3, 86}}:    KindGofundmemeBondingCurvePool,
}

// Account type names, one per generated layout.
const (
	KindPumpfunBondingCurve            AccountKind = "PumpfunBondingCurve"
	KindPumpfunGlobal                  AccountKind = "PumpfunGlobal"
	KindPumpswapPool                   AccountKind = "PumpswapPool"
	KindPumpswapGlobalConfig           AccountKind = "PumpswapGlobalConfig"
	KindRaydiumLaunchlabPoolState      AccountKind = "RaydiumLaunchlabPoolState"
	KindRaydiumLaunchlabGlobalConfig   AccountKind = "RaydiumLaunchlabGlobalConfig"
	KindRaydiumLaunchlabPlatformConfig AccountKind = "RaydiumLaunchlabPlatformConfig"
	KindMeteoraDbcVirtualPool          AccountKind = "MeteoraDbcVirtualPool"
	KindMeteoraDbcPoolConfig           AccountKind = "MeteoraDbcPoolConfig"
	KindMoonitCurveAccount             AccountKind = "MoonitCurveAccount"
	KindMoonitConfigAccount            AccountKind = "MoonitConfigAccount"
	KindHeavenLiquidityPoolState       AccountKind = "HeavenLiquidityPoolState"
	KindHeavenProtocolConfig           AccountKind = "HeavenProtocolConfig"
	KindVertigoPool                    AccountKind = "VertigoPool"
	KindGofundmemeBondingCurvePool     AccountKind = "GofundmemeBondingCurvePool"
)

// ProgramOf maps each generated account type to its owning program.
var ProgramOf = map[AccountKind]string{
	KindPumpfunBondingCurve:            "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P",
	KindPumpfunGlobal:                  "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P",
	KindPumpswapPool:                   "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA",
	KindPumpswapGlobalConfig:           "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA",
	KindRaydiumLaunchlabPoolState:      "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj",
	KindRaydiumLaunchlabGlobalConfig:   "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj",
	KindRaydiumLaunchlabPlatformConfig: "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj",
	KindMeteoraDbcVirtualPool:          "dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN",
	KindMeteoraDbcPoolConfig:           "dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN",
	KindMoonitCurveAccount:             "MoonCVVNZFSYkqNXP6bxHLPL6QQJiMagDL3qcqUQTrG",
	KindMoonitConfigAccount:            "MoonCVVNZFSYkqNXP6bxHLPL6QQJiMagDL3qcqUQTrG",
	KindHeavenLiquidityPoolState:       "HEAVEnMX7RoaYCucpyFterLWzFJR8Ah26oNSnqBs5Jtn",
	KindHeavenProtocolConfig:           "HEAVEnMX7RoaYCucpyFterLWzFJR8Ah26oNSnqBs5Jtn",
	KindVertigoPool:                    "vrTGoBuy5rYSxAfV3jaRJWHH6nN9WK4NRExGxsk1bCJ",
	KindGofundmemeBondingCurvePool:     "GFMioXjhuDWMEBtuaoaDPJFPEnL2yDHCWKoVPhj1MeA7",
}
